name : Publish to Github Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        uses: sudo apt install emacs-nox --yes

      - name: Build the site
        uses: ./build.sh

      - name: Publish content to Github pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
	with:
	  branch: gh-pages
	  folder: public